using System;
using System.IO;
using System.Linq;
using Mutateful.Cli;

namespace Mutateful.Utility
{
    public static class TestUtilities
    {
        public static void AppendUnitTest(string formula, byte[] inputData, byte[] outputData)
        {
            using (var file = File.AppendText(@"GeneratedUnitTests.txt"))
            {
                file.Write($"// Test generated by mutate4l from formula: {formula}{Environment.NewLine}" +
                           $"[TestMethod]{Environment.NewLine}" +
                           $"public void NameThisMethod(){Environment.NewLine}" +
                           $"{{{Environment.NewLine}" +
                           $"    byte[] input = {{ {Utilities.GetByteArrayContentsAsString(inputData.Take(inputData.Length - CliHandler.UnitTestDirective.Length).ToArray())} }};{Environment.NewLine}" +
                           $"    byte[] output = {{ {Utilities.GetByteArrayContentsAsString(outputData)} }};{Environment.NewLine}" +
                           $"{Environment.NewLine}" +
                           $"    TestUtilities.InputShouldProduceGivenOutput(input, output);{Environment.NewLine}" +
                           $"}}{Environment.NewLine}{Environment.NewLine}");
            }
        }
    }
}